# These come from solitude. Go there for detailed comments.
SOURCE_BANGO = 1

TYPE_PAYMENT = 0
TYPE_REFUND = 1
TYPE_REVERSAL = 2

STATUS_PENDING = 0
STATUS_COMPLETED = 1
STATUS_CHECKED = 2
STATUS_RECEIVED = 3
